name: tests

on: [workflow_dispatch, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip install git+https://github.com/metomi/rose@master
          pip install --no-deps ."[all]"
